### PR TITLE
Added configuration change support.

### PR DESCRIPTION
**Pull request by delirehberi**
Code reformat.

### CODE REVIEW

**Comment by delirehberi** [comment]
@coffeetalkh  can you add me as contributor for this repo?

**Comment by imehdihosseini** [comment]
@delirehberi  Thanks emre, i added you as Datium collaborators, and i followed your pull request changes, timezone config is a necessary feature for Datium and i think we should also support htaccess or other default possibilities for default time zone.

**Comment by delirehberi** [comment]
I think we don't touch default time zone ever. I can't find any other solution for now, but i will think it.

**Comment by imehdihosseini** [comment]
We can check default status by `date_default_timezone_get();` and then do the best solution for it.

**Pull request merged**
